// layout.js or layout.tsx
import { Poppins } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./context/ThemeContext";

// Load Poppins font with desired weights
const poppins = Poppins({
  weight: ["100", "300", "400", "500", "600", "700"],
  subsets: ["latin"], // specify the subset
});

export const metadata = {
  title: "John Lery's Portfolio Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className + " antialiased"}>
        <ThemeProvider> {children} </ThemeProvider>
      </body>
    </html>
  );
}
